FROM alpine:3

ARG UNIMUS_VERSION="-%20Latest"

LABEL org.opencontainers.image.authors="JoKneeMo <https://github.com/JoKneeMo>" \
    org.opencontainers.image.source="https://github.com/JoKneeMo/unimus-docker" \
    org.opencontainers.image.title="Unimus Core" \
    org.opencontainers.image.version="${UNIMUS_VERSION}"

RUN apk update && apk add --no-cache \
    curl \
    ca-certificates \
    wget \
    less \
    tzdata \
    iputils \
    tini \
    bash \
    openjdk21-jre-headless \
    && addgroup -S -g 1000 unimus \
    && adduser -S -D -u 1000 -G unimus unimus \
    && echo "UTC" > /etc/timezone

RUN if [ "${UNIMUS_VERSION}" = "dev" ]; then \
        DOWNLOAD_URL="https://download.unimus.net/unimus-core-dev/Unimus-Core.jar"; \
    else \
        DOWNLOAD_URL="https://download.unimus.net/unimus-core/${UNIMUS_VERSION}/Unimus-Core.jar"; \
    fi \
    && curl -L "${DOWNLOAD_URL}" --create-dirs -o /opt/unimus-core/Unimus-Core.jar \
    && mkdir -p \
        /etc/unimus-core \
        /var/log/unimus-core \
    && touch \
        /etc/unimus-core/unimus-core.properties \
    && chown -R unimus:unimus \
        /opt/unimus-core \
        /etc/unimus-core \
        /var/log/unimus-core \
        /etc/timezone

COPY --chmod=755 entrypoint-core.sh /entrypoint.sh

WORKDIR /opt/unimus-core

USER unimus

ENV TZ=UTC \
    MAKE_PROPERTIES=true

ENTRYPOINT ["tini", "-g", "--", "/entrypoint.sh"]
